export const REDUCE_CREATE_GAME = 'REDUCE_CREATE_GAME'
export const REDUCE_EDIT_GAME = 'REDUCE_EDIT_GAME'
export const REDUCE_EDIT_SCORE = 'REDUCE_EDIT_SCORE'

export const REDUCE_EDIT_USER = 'REDUCE_EDIT_USER'
