export const rows = [
  { label: 'aces' },
  { label: 'twos' },
  { label: 'threes' },
  { label: 'fours' },
  { label: 'fives' },
  { label: 'six' },
  { label: 'threeOf' },
  { label: 'fourOf' },
  { label: 'fullHouse' },
  { label: 'smSt' },
  { label: 'lgSt' },
  { label: 'free' },
  { label: 'yahtzee' },
]
